version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongoData:/data/db
    networks:
      - trivia-network

  backend:
    build: ./backend
    container_name: trivia-backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DB_URL=mongodb://mongo:27017/final_project
    depends_on:
      - mongo
    command: >
      sh -c "chmod +x ./run-migrations.sh && ./run-migrations.sh"
    networks:
      - trivia-network

  frontend:
    build: ./frontend
    container_name: trivia-frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - WDS_SOCKET_PORT=3001
    depends_on:
      - backend
    networks:
      - trivia-network

networks:
  trivia-network:
    driver: bridge

volumes:
  mongoData:
